### ISSUE TITLE
How to reduce the height?

### ISSUE THREAD

**Issue by hwqing** [furcan/KioskBoard#22]
Dear,

Is there any way to reduce the height of keyboard panel, and also smaller size key?
Currently the height of keyboard panel is about half of my screen height, and will easily cover other elements.

**Comment by furcan** [comment]
Hi @hwqing 

There is no optional way to reduce the height of the keyboard.

Maybe you can use CSS to do this.

```css
div#KioskBoard-VirtualKeyboard {
    transform: scaleY(0.75);
    transform-origin: bottom center;
}
```

Thanks,
Furkan.
